export const FORMATOS_VISITA: any = {
    'chequeo_estandarizado': {
        nombreArchivoPdf: 'chequeo_de_visitas_estandarizada.pdf',
        totalItems: 60,
        diccionario: {
    1: "Hacer carpeta con el historial de visitas.", // [cite: 55]
    2: "Aseo y organización general del restaurante (terraza, vidrios, pisos, madera).", // [cite: 55]
    3: "Iluminación general (avisos encendidos, lámparas).", // [cite: 55]
    4: "Presentación vitrina de helados (orden, limpieza, y decoración con tarros globo y Tang).", // [cite: 55]
    5: "Barra de ensalada (presentación, esta surtida, ingredientes completos, habladores de producto).", // [cite: 55]
    6: "Mesas y sillas que estén alineadas, limpias y en buen estado (incluye ganchos para cartera).", // [cite: 55]
    7: "Código QR en buen estado.", // [cite: 55]
    8: "Ventiladores y aires acondicionados limpios.", // [cite: 55]
    9: "Espejos del comedor limpios.", // [cite: 55]
    10: "Muebles de cristal y madera (aseo, organización).", // [cite: 55]
    11: "Aseo general baños de clientes (espejo, cambiador de bebes, canecas, papel surtido).", // [cite: 55]
    12: "Estado, disponibilidad y ubicación de cartas.", // [cite: 55]
    13: "Campanas de extracción limpias y brillantes.", // [cite: 55]
    14: "Estado de canecas (tapas, bolsas, marcadas).", // [cite: 55]
    15: "Estado de elementos de publicidad (helados de temporada en caleido, en barra de helados avisos superiore completos y trípticos).", // [cite: 55]
    16: "La pieza de medición de Los pasa cuentas tienen experiencia al cliente.", // [cite: 55]
    17: "Presentación del personal (uniforme limpio, planchado, ropa interior blanca maquillaje peinado, malla, moña negra, uñas cortas etc).", // [cite: 55]
    18: "Escarapela del personal completa.", // [cite: 55]
    19: "Zona de empaque organizada y elementos completos (bandejas, bolsa de papel grandes, stickers, marcadores tapas).", // [cite: 55]
    20: "Actitud del personal o incidente relacionado durante el servicio.", // [cite: 55]
    21: "Hay acompañamiento del cliente a la mesa.", // [cite: 55]
    22: "La mesera se acerca pronto y a la mesa.", // [cite: 55]
    23: "La mesera se acerca pronto y se presenta.", // [cite: 55]
    24: "La mesera vende la primera bebida, se ofrecen entradas, se ofrecen postres y cafés.", // [cite: 55]
    25: "El montaje de las mesas es el correctolo , realizan por el lado derecho y utilizan la bandeja para hacerlo.", // [cite: 55]
    26: "Realizar correctamente el uso de bandejas para entregar producto y retirar menaje, se cuida de no exceder la carga permitida.", // [cite: 64]
    27: "La auxiliar recoge a tiempo y de forma ordenada el menaje ofreciendo siempre otro producto.", // [cite: 64]
    28: "Envió de PRIMERO TODOS correctamente.", // [cite: 64]
    29: "Hay faltante de producto por gestión de lideres.", // [cite: 64]
    30: "Decoración y presentación de platos cumple con lo establecido en el área.", // [cite: 64]
    31: "Agilidad en la entrega de productos, evitando que éste expuesto causando alteración en calidad y temperatura.", // [cite: 64]
    32: "Se cumplen los tiempos de entrega por parte de las áreas en cocina.", // [cite: 64]
    33: "Se maneja de manera adecuada el pan de cortesía.", // [cite: 64]
    34: "Se despeja la mesa para realizar el cobro.", // [cite: 64]
    35: "Entrega cuenta en la mesa (verificación de lo facturado, по hay clientes pagando en la caja).", // [cite: 64]
    36: "La cajera es amable, aborda y da la bienvenida al cliente.", // [cite: 64]
    37: "Hay ofrecimiento de venta en la barra de helados.", // [cite: 64]
    38: "Presentación y organización de caja.", // [cite: 64]
    39: "Presentación caja repique (sin decoración y buen estado).", // [cite: 64]
    40: "Existencia de certificado de regalo.", // [cite: 64]
    41: "Fachada limpia y despejada.", // [cite: 64]
    42: "Jardines y materas limpias y en buen estado.", // [cite: 64]
    43: "Parqueadero limpios y despejados.", // [cite: 64]
    44: "Las estaciones están surtidas y organizadas (salero, pimienta, azucarera etc).", // [cite: 64]
    45: "El personal de servicio externo cuenta con implementos personales necesarios para la operación (coge ollas, libreta, toma pedidos, esfero, y conoce la labor de venta).", // [cite: 64]
    46: "La anfitriona muestra una actitud proactiva y servicial en la operación.", // [cite: 64]
    47: "Implementos completos en la zona de pan (pinzas, papel parafinado, pan fresco, canastas).", // [cite: 64]
    48: "Caja de té surtida y en buen estado.", // [cite: 64]
    49: "Sillas de bebe dispuesta para su buen uso, asedas y en buen estado.", // [cite: 64]
    50: "El personal desinfecta sus manos ante de abandonar la zona de platero.", // [cite: 77]
    51: "Correcta separación de residuos (contenido de canecas).", // [cite: 79]
    52: "El personal cumple con buen uso de tapabocas.", // [cite: 82]
    53: "Conocimiento y labor de venta de productos nuevo de la carta.", // [cite: 82]
    54: "Durante el servicio se presentaron errores de envío de producto o incompletos.", // [cite: 84]
    55: "Comunicación eficiente entre los diferentes puestos de cocina que permite la agilidad y el ensamble de pedidos correctamente.", // [cite: 93]
    56: "El cliente recibe la orden como lo pide o se cometen errores por falta de confirmación del pedido.", // [cite: 94]
    57: "Las meseras realiza seguimiento a sus mesas, evita que el cliente deba levantar la mano.", // [cite: 95]
    58: "Se controla el tiempo promesa de entrega al cliente en domicilios internos o externos.", // [cite: 96]
    59: "Interacción de la líder con los clientes y el equipo de servicio.", // [cite: 97]
    60: "Solicitar a la líder del servicio que le muestre los indicadores de venta y evaluaciones realizadas al personal (relacione cifras relevantes)." // [cite: 98, 99, 100]
        }
    }
}